#: import SlideTransition kivy.uix.screenmanager.SlideTransition

<MainLayout>:
    screen_manager: screen_manager
    ScreenManager:
        id: screen_manager
        timestamp: ""
        daystamp: ""
        mail_address: ""
        transition: SlideTransition()
        LoginScreen:
            id: login_screen
        AgreementScreen:
            id: agreement_screen
        CaptureScreen:
            id: capture_screen
        PendingScreen:
            id: pending_screen
		TakeOutScreen:
			id: takeout_screen
		ScreenSaver:
			id: screen_saver

<LoginScreen>:
    name: 'login'
	message_text: ''
	mail_input: mail_input
	on_pre_enter:
	    mail_input.text=""
	on_enter:
	    mail_input.focus=True
    BoxLayout:
        orientation: 'vertical'
        padding: 20  # Border around the widgets inside this boxlayout
        spacing: 15  # Spacing between the widgets inside this boxlayout
        Label:
            font_size: 30
            text: "Bitte geben Sie hier Ihre E-mail Adresse ein"
            size_hint_y: .2  # => 20% of normal size (LoginScreen.height/4*0.3)
        TextInput:
            id: mail_input
            font_size: 30
            multiline: False
			text: ""
			focus: True
            size_hint_y: None  # Must set to None to honor height property
            height: 50
        Button:
            size_hint_y: .4
            font_size: 30
            text: "Weiter"
            on_press:
                root.next(mail_input.text)
		Label:
			id: message
			font_size: 30
			text: root.message_text

<AgreementScreen@Screen>:
    name: "agreement"
    BoxLayout:
        orientation: 'vertical'
		padding: 20  
        Label:
			font_size: 30
			multiline: True
            text: "Ich bin damit einverstanden dass meine E-mail Adresse \nvon der Firma Brändli Obst- und Weinbau Au am Zürichsee \nfür saisonale Informationen genutzt werden darf."
        BoxLayout:
			padding: 20  # Border around the widgets inside this boxlayout
			spacing: 15  # Spacing between the widgets inside this boxlayout
            Button:
				font_size: 30
                text: "Nein"
                on_press:
                    root.manager.current = "login"
            Button:
				font_size: 30
                text: "Ja"
                on_press:
                    #root.manager.current = "capture"
					root.if_agree()
<CaptureScreen>:
    name: 'capture'
    float_layout: float_layout
    FloatLayout:
        id: float_layout


<StartButton@AnchorLayout>:
    padding: 0, 10
    anchor_x: 'center'
    anchor_y: 'bottom'
    action: None
    Button:
        size_hint: None, None
        size: 300, 100
		font_size: 30
        text: "Start"
        on_press:
            root.action()

<Countdown>:
    count: 1
    action: None
    BoxLayout:
        size_hint: 0.3, 0.3
        canvas.before:
            Color:
                rgba: 0,0,0,.5
            Rectangle:
                size: self.size
                pos: self.pos
        Label:
            font_size: 45
            bold: True
            text: str(root.count)


<PendingScreen@Screen>:
    name: 'pending'
    #shown_text: ""
    BoxLayout:
        orientation: 'vertical'
		Widget:
			size_hint_y: .1
        Image:
            source: 'loader.zip'
            anim_delay: 0.1
        Label:
			font_size: 30
			multiline: True
            #text: root.shown_text
			text: "Bitte haben sie einen Moment Geduld"
        #Button:
            #text: "okay"
            #on_press:
                #root.show_screen_saver()
				
<TakeOutScreen@Screen>:
    name: 'takeout'
    shown_text: ""
    BoxLayout:
        orientation: 'vertical'
		Widget:
			size_hint_y: .1
        Label:
			font_size: 30
			multiline: True
            text: "Bitte entnehmen sie Ihr Photo.\n\nWir bedanken uns und wünschen Ihnen einen \nangenehmen Aufenthalt im Gasthof Oberort."

<ScreenSaver>:
	name: 'screen_saver'
	Image:
	    source: root.image_source
	#Button:
		#size_hint_y: .4
        #text: "okay"
        #on_press:
            #root.show_login()